### PR TITLE
Move CMFControllerForms to BrowserViews

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by davisagli** [comment]
LGTM. Hmm, why isn't mr.roboto doing checks here?

**Comment by tomgross** [comment]
http://jenkins.plone.org/job/pull-request-5.0/1527

**Comment by jensens** [comment]
we have test failures.

**Comment by pbauer** [comment]
@tomgross can you rebase and finish this? Aside from the old login (which will be replaced by `plone.login`) `CMFEditions` is the last user of `CMFFormController` and removing that would be great!

**Comment by gforcada** [comment]
The rebase was effortlessly, let's see what Jenkins says, though.

@tomgross I hope you do not mind that I rebased the branch :smiley:

**Comment by tomgross** [comment]
I looked into this again. It is a little bit tricky since the product registeres some formcontroller scripts which take care of moving at objects out of the temporary folder. These scripts are not triggered in the BrowserView setup. I‘ll investigate further to find a solution.

**Comment by pbauer** [comment]
Looks good 😄

**Pull request merged**
