### PR TITLE
Prefer newer assert methods

### PR DESCRIPTION
**Pull request by davilima6**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
LGTM. I have started Jenkins jobs. Should have a changelog entry. When the jobs runs, I would say you can add that changelog entry and merge it yourself.

**Comment by davilima6** [comment]
@mauritsvanrees, thanks! I thought of leaving this included as part of the entry for preparing for Py 2/3 compatibility since it's just a detail others devs probably won't care much about. Agree?

**Comment by mauritsvanrees** [comment]
ah, sure, fine to leave it out.
And... Jenkins just went green, so I will merge.

**Comment by davilima6** [comment]
Thank you! :)

**Comment by davilima6** [comment]
@mauritsvanrees, @gforcada: It'd be nice to replace all failUnless* methods with asserts*. I saw you both making bulk changes a few times in core deps. Would you have a script I could base upon to accomplish that (just go in all src/ checkouts directories, create a branch, do a sed, commit and push)? We may schedule sometime in IRC to coordinate that if you'd like.

**Comment by gforcada** [comment]
@davilima6 I don't have any script at hand actually, plain sed and then repeat the same command on all repositories affected :-)

As for scheduling this on IRC: I would very much like to give this kind of really easy tasks to newcomers, now that GSOC is approaching and candidates are starting their community bounding, it will be very good to see how they tackle this easy task.

Creating an issue on CMFPlone pointing to all packages that need to be updated with some hints on how to do the changes would be probably enoguh, then we can ping @cewing and that could get our GSOC-to-be started 👍

**Comment by gforcada** [comment]
Same goes to code analysis cleanups as well.

**Comment by davilima6** [comment]
Ok, sounds good.

**Comment by mauritsvanrees** [comment]
When I need to do something in lots of packages, like recently adding a `setup.cfg`, I usually create a shell one-liner, just a for-loop with a few commands.
For changing a string within a package, I have an ugly shell script:

```
#! /bin/sh
if test $# -ne 2; then
    cat <<EOF
Usage: $0 "Original term" "New term"

Recursively searches for files in the current directory.
Replaces all occurences of "Original term" by "New term".

SO THIS IS DANGEROUS!

NO WARRANTY AT ALL.  ASSUME THIS DELETES ALL YOUR FILES!
EOF
    exit 0
fi

# For svn and bazaard check 'bzr/svn info'.  This prints zero lines to
# stdout (1 to stderr) when there this directory is not from bazaar/svn.

# Try git.
if test $(git status | wc -l) -eq 0; then
    # Try svn
    if test $(svn info 2> /dev/null | wc -l) -eq 0; then
        # Try bazaar.
        if test $(bzr info 2> /dev/null | wc -l) -eq 0; then
            # Try Mercurial
            if test $(hg status > /dev/null && echo "okay" || echo "booh") = 'booh'; then
                echo "No git/svn/bzr/hg found.  Bailing out for safety."
                exit 1
            fi
        fi
    fi
fi

# TODO: this does not work for files/dirs with spaces.
for FILE in $(find . -name "*py" -o -name '*txt' -o -name '*zcml' -o -name '*.xml' -o -name '*pt' -o -name '*.po' -o -name '*.pot' -o -name '*sql' -o -name '*.rst' -o -name '*.cfg' -o -name '*.css'  -o -name '*.dtml' -o -name '*.tex' -o -name '*.conf' -o -name '*.html' -o -name '*.conf' -o -name '*.xsd' -o -name '*.sass' -o -name '*.js' -o -name '*.jinja2' -o -name '*.feature' -o -name '*.ini' -o -name '*.in' -o -name '*.json' -o -name '*rc' -o -name '*.robot'); do
    if test -f $FILE; then
        if test $(grep -c "$1" "$FILE") -ge 1; then
            echo "Refactoring $FILE"
            cp -a "$FILE" "$FILE.bak"
            cat "$FILE.bak" | sed "s|$1|$2|g" > "$FILE"
            if test $? -eq 0; then
                rm "$FILE.bak"
            else
                echo "ERROR refactoring file $FILE"
                echo "Keeping original $FILE.bak"
                echo "Please investigate.  Bailing out prematurely."
                exit 1
            fi
        fi
    fi
done
```

**Pull request merged**
