### PR TITLE
Add Python 2 / 3 compatibility

### PR DESCRIPTION
**Pull request by davilima6**

### CODE REVIEW

**Comment by jensens** [comment]
LGTM, except that ``bootstrap.py`` should not be touched (rather both, ``bootstrap.py`` and ``buildout.cfg`` should be removed here).

**Comment by davilima6** [comment]
@jensens, fixed

**Comment by davilima6** [comment]
I'm having trouble getting passed of the flakiest `Robot.Test Querystring.Scenario: Location query`. Tried many build already. Any hints, @mauritsvanrees, @jensens ? http://jenkins.plone.org/job/pull-request-5.1/850/robot/Robot/Test%20Querystring/Scenario%3A%20Location%20query/

**Comment by mauritsvanrees** [comment]
I don't really have hints on that one. Maybe the test should be remade from the ground up.
But that test is marked as noncritical. It does not break this build.
There are [6 failures](http://jenkins.plone.org/job/pull-request-5.1/850/testReport/) in CMFEditions and in plone.app.versioningbehavior. So I wonder if you are overlooking those. I know *I* have overlooked them at some point. The red robot failure attracts the eye.

**Comment by davilima6** [comment]
Yes, @mauritsvanrees, that was the case. Thanks one more time for spotting! Fixed now!

**Pull request merged**
