### PR TITLE
Remove 'AT objects only' in at_edit_autoversion policy title

### PR DESCRIPTION
**Pull request by cedricmessiant**
This comment seems deprecated as we also use this policy for dexterity content types (see plone.app.versioningbehavior README)

### CODE REVIEW

**Comment by jensens** [comment]
``class` and ``name`` are also suggesting its AT only, are you sure? if yes I'd clean up the whole thing in order to reduce future-developers headache instead of just fixing the label.

**Comment by vincentfretin** [comment]
Yes, at_edit_autoversion works with Dexterity.
Please don't change the at_edit_autoversion id, I really don't want to modify all my projects to change the repositorytool.xml file in the profile. For the class I guess we can change the name and add a comment to say the id shouln't be changed because it's used in repositorytool.xml.

**Comment by jensens** [comment]
:+1: for renaming the class and *sigh* :) then lets keep the id and add a comment.

**Comment by jensens** [comment]
todo: 
- add little note to change log
- add note in code/xml why the name is as it is

**Comment by cedricmessiant** [comment]
Done. Tests are ok locally

**Comment by jensens** [comment]
full tests tests are running here: 
http://jenkins.plone.org/job/pull-request-5.0/186/
http://jenkins.plone.org/job/pull-request-4.3/64/

**Comment by jensens** [comment]
next trial
http://jenkins.plone.org/job/pull-request-5.0/192/
http://jenkins.plone.org/job/pull-request-4.3/65/

**Comment by cedricmessiant** [comment]
it seems that these tests weren't triggered by this pull request (no CMFEditions in there)

**Comment by jensens** [comment]
well, the output is a bit messy. but it checks it out, see console output::

   + sed -ie s/^Products.CMFEditions\s.*/Products.CMFEditions = git git:\/\/github.com\/plone\/Products.CMFEditions.git branch=remove-at-related-comment/g sources.cfg

**Comment by jensens** [comment]
wait, bit no "cloned" at mr.developer, youre right.

**Comment by jensens** [comment]
Also console output of 5.0 is truncated. So, lets first try with 5.0 again and see what the output is: http://jenkins.plone.org/job/pull-request-5.0/194/

**Comment by jensens** [comment]
ok, at least "mr.developer: Cloned 'Products.CMFEditions' with git." and before it replaced the branch with yours.

**Comment by jensens** [comment]
That failures are really strange for a minor change like this is.

**Comment by ebrehault** [comment]
@tisto, could it be a test isolation issue (again) ?

**Comment by mauritsvanrees** [comment]
I had a similar problem with Jenkins last week, where test failures with plone.app.testing were reported but the real problem was an error in my code that was only visible when you inspected the console log.

For this pull request I wonder if migration is needed. In old sites the repository tool will have a policy that points to class `ATVersionOnEditPolicy` and that class is gone now. I don't see obvious failures when I test it manually though.

Oh, but I do see a test failure locally. On a hunch I ran the plone.app.upgrade tests and they give an error when using the branch of this pull request:

```
Running plone.app.upgrade.v50.testing.plone.app.upgrade:4.0 -> 5.0 tests:
  Tear down plone.app.testing.bbb.PloneTestCase:Functional in 0.000 seconds.
  Tear down plone.app.testing.bbb.PloneTestCaseFixture in 0.012 seconds.
  Set up plone.app.upgrade.v50.testing.RealUpgradeLayer Traceback (most recent call last):
  File "/Users/mauritsvanrees/shared-eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 400, in run_layer
    setup_layer(options, layer, setup_layers)
  File "/Users/mauritsvanrees/shared-eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 708, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/Users/mauritsvanrees/shared-eggs/zope.testrunner-4.4.4-py2.7.egg/zope/testrunner/runner.py", line 713, in setup_layer
    layer.setUp()
  File "/Users/mauritsvanrees/shared-eggs/plone.app.testing-5.0b5-py2.7.egg/plone/app/testing/helpers.py", line 350, in setUp
    self.setUpPloneSite(portal)
  File "/Users/mauritsvanrees/community/plone-coredev/5.0/src/plone.app.upgrade/plone/app/upgrade/v50/testing.py", line 18, in setUpPloneSite
    app._importObjectFromFile(path, verify=0)
  File "/Users/mauritsvanrees/shared-eggs/Zope2-2.13.22-py2.7.egg/OFS/ObjectManager.py", line 645, in _importObjectFromFile
    filepath, customImporters=customImporters)
  File "/Users/mauritsvanrees/shared-eggs/ZODB3-3.10.5-py2.7-macosx-10.4-x86_64.egg/ZODB/ExportImport.py", line 92, in importFile
    t.savepoint(optimistic=True)
  File "/Users/mauritsvanrees/shared-eggs/transaction-1.1.1-py2.7.egg/transaction/_transaction.py", line 260, in savepoint
    self._saveAndRaiseCommitishError() # reraises!
  File "/Users/mauritsvanrees/shared-eggs/transaction-1.1.1-py2.7.egg/transaction/_transaction.py", line 257, in savepoint
    savepoint = Savepoint(self, optimistic, *self._resources)
  File "/Users/mauritsvanrees/shared-eggs/transaction-1.1.1-py2.7.egg/transaction/_transaction.py", line 690, in __init__
    savepoint = savepoint()
  File "/Users/mauritsvanrees/shared-eggs/ZODB3-3.10.5-py2.7-macosx-10.4-x86_64.egg/ZODB/Connection.py", line 1123, in savepoint
    self._commit(None)
  File "/Users/mauritsvanrees/shared-eggs/ZODB3-3.10.5-py2.7-macosx-10.4-x86_64.egg/ZODB/Connection.py", line 587, in _commit
    self._importDuringCommit(transaction, *self._import)
  File "/Users/mauritsvanrees/shared-eggs/ZODB3-3.10.5-py2.7-macosx-10.4-x86_64.egg/ZODB/ExportImport.py", line 176, in _importDuringCommit
    pickler.dump(unpickler.load())
AttributeError: 'module' object has no attribute 'ATVersionOnEditPolicy'
```

Note that the summary of the tests gives no test failures, only an error, so maybe this is why no failed test for plone.app.upgrade is reported by Jenkins:

```
Total: 20 tests, 0 failures, 1 errors, 0 skipped in 23.030 seconds.
```

Oh, and note that since this morning there is a new release of CMFEditions and the coredev 5.0 branch is using that one. So for a new Jenkins run I guess you would need to add CMFEditions to the checkouts again, unless I have the wrong idea about how this should work.

BTW, @cedricmessiant, for starting a pull request job on Jenkins, you can probably do that yourself. You should be able to login on jenkins.plone.org with your github account, go to 'pull request 5.0' (and 4.3 too I guess), on the left hand side click on 'Build with Parameters', and fill in the pull request url in the form.

**Comment by jensens** [comment]
try again http://jenkins.plone.org/job/pull-request-5.0/312/

**Comment by jensens** [comment]
3 failing tests.

**Comment by jensens** [comment]
There was no activity on this for a while. I close this request for now. If you plan to work further on this please reopen and go on.

**Pull request closed without merging**
