### PR TITLE
Plone 6: Remove support for Archetypes, Zope 2, Python 2

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This does the most important part of issue #74.
I have created branch 3.x from master before doing this, and have updated coredev branch 5.2 to use it.

It's a big diff. You may want to look at the individual commits instead.

cc @plone/framework-team as it can be seen as a part of https://github.com/plone/Products.CMFPlone/issues/2775

Possible future work: In an upgrade step we could go through the modifiers (and maybe policies) and remove any broken ones. This could be code in plone.app.upgrade. Or maybe I should add it here in CMFEditions, either in this PR or a new one after it is merged. But an upgrade site should already work fine even when there are broken modifiers and policies, as they are now detected and ignored.

### CODE REVIEW

**Comment by jensens** [comment]
Since this targets Plone 6 and it is an obvious step to remove dead AT code we can just merge this or does the framework team need to decide here?

**Comment by ale-rt** [comment]
I started having a look at it. It looks good to me, but I wanted to do a proper review, which will take some time.
BTW if you want to merge this, for me it is fine ;)

**Comment by ale-rt** [comment]
P.s.: thanks for that!

**Review by ale-rt — APPROVED** [review]
LGTM, has explained I did not do a full review but just skimmed the patch. I am fine with merging this but maybe you want some other approver

**Comment by mauritsvanrees** [comment]
Okay, I merge. :-)
Thanks.

**Pull request merged**
